port: 7880
rtc:
    tcp_port: 7881
    udp_port: 7882
    enable_loopback_candidate: true
    use_external_ip: false
    # 注释掉下面这一行，不要强制指定 node_ip，让它自动绑定
    # node_ip: "192.168.2.220"
keys:
    devkey: secret